# For local development

version: "3.8"
services:
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     target: dev
  #   ports:
  #     - 3000:3000
  matching-service:
    container_name: matching-service
    build:
      context: ./matching-service
      target: dev
    ports:
      - 8080:8080
  user-service:
    container_name: user-service
    build:
      context: ./user-service
      target: dev
    ports:
      - 8081:8080
