# For local development

version: "3.8"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: dev
    environment:
      - MATCHING_SERVICE_DOMAIN="http://matching-service:8080"
    ports:
      - 3000:3000
  matching-service:
    container_name: matching-service
    build:
      context: ./matching-service
      target: dev
    ports:
      - 8080:8080
