@startuml abc
!include style.puml

actor "User" as User

box User Service USER_SERVICE_COLOR_T1
	participant "User Service" as UserService
end box

box Matching Service MATCHING_SERVICE_COLOR_T1
	participant "Matching Service" as MatchingService
end box

User -> UserService : login(username, password)
activate UserService
alt valid credentials
	User <-- UserService : accessToken
else else
	User <-- UserService : httpErrorCode: 400
	deactivate UserService
end


User -> UserService : verifyAccessToken(accessToken) 
activate UserService
alt access token is valid
	User <-- UserService : httpStatusCode: 200
	User -> MatchingService : requestMatch(difficultyLevel)
	activate MatchingService
	opt found peer within 30 seconds
		User <-- MatchingService : matchRoomNumber
		deactivate MatchingService
	end
else else
	User <-- UserService : httpStatusCode: 401
	deactivate UserService
end

@enduml

'========= ADDITIONAL COMMANDS ============='
'=== TO CREATE A NEW CLASS ==='
' create CommandResult
' activate CommandResult
' deactivate CommandResult