name: "Run tests for all services"

on:
  pull_request:
    branches: ["main"]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker images
        run: |
          docker build --target test -t frontend-test ./frontend
          docker build --target test -t user-service-test ./user-service
          docker build --target test -t matching-service-test ./matching-service
          docker build --target test -t collaboration-service-test ./collaboration-service

      - name: Run the tests
        run: |
          docker run --name frontend-test-container frontend-test
          docker run --name user-service-test-container user-service-test
          docker run --name matching-service-test-container matching-service-test
          docker run --name collaboration-service-test-container collaboration-service-test
